name: test-work
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: test1
       run: echo " build is running "
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: echo " test is running "
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test3
        run: echo " app is deployed "
        
      
